apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-log-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: activity-log-api
  template:
    metadata:
      labels:
        app: activity-log-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: ghcr.io/ramymohamed47/event-driven-microservice:latest
          imagePullPolicy: Always
          command: ['node', 'dist/api.js']
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: activity-log-config
            - secretRef:
                name: activity-log-secrets
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
