apiVersion: v1
kind: Secret
metadata:
  name: activity-log-secrets
  namespace: activity-logs
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://replace-me
  KAFKA_SASL_MECHANISM: scram-sha-512
  KAFKA_SASL_USERNAME: replace-me
  KAFKA_SASL_PASSWORD: replace-me
