apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-log-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: activity-log-worker
  template:
    metadata:
      labels:
        app: activity-log-worker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: worker
          image: ghcr.io/ramymohamed47/event-driven-microservice:latest
          imagePullPolicy: Always
          command: ['node', 'dist/worker.js']
          ports:
            - name: health
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: activity-log-config
            - secretRef:
                name: activity-log-secrets
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: health
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
